#ifndef DECAL_VOLUME_RENDERING_CSHARED_H
#define DECAL_VOLUME_RENDERING_CSHARED_H

#include "decal_volume_cshared.h"

#define REGISTER_CBUFFER_DECAL_VOLUME_CONSTANTS				MAKE_REGISTER_CBUFFER( 2 )

#define REGISTER_TEXTURE_DIFFUSE_TEXTURE					MAKE_REGISTER_SRV( 2 )
#define REGISTER_SAMPLER_DIFFUSE_SAMPLER					MAKE_REGISTER_SAMPLER( 2 )

MAKE_FLAT_CBUFFER( CbDecalVolumeRenderingConstants, REGISTER_CBUFFER_DECAL_VOLUME_CONSTANTS )
{
	CBUFFER_FLOAT4( renderTargetSize ); // rcp in zw
	CBUFFER_UINT4( dvCellCount );
	CBUFFER_FLOAT4( colorMultiplier );
	CBUFFER_FLOAT4( nearFarPlane );
};

#endif // DECAL_VOLUME_RENDERING_CSHARED_H
