#ifndef DECAL_VOLUME_RENDERING_CSHARED_H
#define DECAL_VOLUME_RENDERING_CSHARED_H

#include "HlslFrameworkInterop.h"

#define REGISTER_CBUFFER_DECAL_VOLUME_CONSTANTS				MAKE_REGISTER_CBUFFER( 2 )

#define REGISTER_TEXTURE_DIFFUSE_TEXTURE					MAKE_REGISTER_SRV( 2 )
#define REGISTER_SAMPLER_DIFFUSE_SAMPLER					MAKE_REGISTER_SAMPLER( 2 )

#define DECAL_VOLUME_CLUSTER_DISPLAY_MODE_3D				0
#define DECAL_VOLUME_CLUSTER_DISPLAY_MODE_2D				1

MAKE_FLAT_CBUFFER( CbDecalVolumeRenderingConstants, REGISTER_CBUFFER_DECAL_VOLUME_CONSTANTS )
{
	CBUFFER_UINT4( dvdMode );
	CBUFFER_FLOAT4( dvdRenderTargetSize ); // rcp in zw
	CBUFFER_UINT4( dvdCellCount );
	CBUFFER_FLOAT4( dvdColorMultiplier );
	CBUFFER_FLOAT4( dvdNearFarPlane );
};

#endif // DECAL_VOLUME_RENDERING_CSHARED_H
