#ifndef GLOBAL_SAMPLERS_HLSL
#define GLOBAL_SAMPLERS_HLSL

#include "HlslFrameworkInterop.h"

#define REGISTER_SAMPLER_ANISO_MIPMAP_CLAMP						MAKE_REGISTER_SAMPLER(  0 )
#define REGISTER_SAMPLER_ANISO_MIPMAP_WRAP_U					MAKE_REGISTER_SAMPLER(  1 )
#define REGISTER_SAMPLER_ANISO_MIPMAP_WRAP_V					MAKE_REGISTER_SAMPLER(  2 )
#define REGISTER_SAMPLER_ANISO_MIPMAP_WRAP						MAKE_REGISTER_SAMPLER(  3 )
#define REGISTER_SAMPLER_SHADOWMAP								MAKE_REGISTER_SAMPLER(  4 )
#define REGISTER_SAMPLER_POINT_CLAMP							MAKE_REGISTER_SAMPLER(  5 )
#define REGISTER_SAMPLER_POINT_WRAP								MAKE_REGISTER_SAMPLER(  6 )
#define REGISTER_SAMPLER_POINT_MIP_CLAMP						MAKE_REGISTER_SAMPLER(  7 )
#define REGISTER_SAMPLER_LINEAR_CLAMP							MAKE_REGISTER_SAMPLER(  8 )
#define REGISTER_SAMPLER_LINEAR_WRAP							MAKE_REGISTER_SAMPLER(  9 )
#define REGISTER_SAMPLER_LINEAR_MIP_CLAMP						MAKE_REGISTER_SAMPLER( 10 )
#define REGISTER_SAMPLER_LINEAR_MIP_LINEAR_CLAMP				MAKE_REGISTER_SAMPLER( 11 )
#define REGISTER_SAMPLER_LINEAR_MIPMAP_WRAP_U					MAKE_REGISTER_SAMPLER( 12 )
#define REGISTER_SAMPLER_LINEAR_MIPMAP_WRAP_V					MAKE_REGISTER_SAMPLER( 13 )
#define REGISTER_SAMPLER_LINEAR_MIP_LINEAR_WRAP					MAKE_REGISTER_SAMPLER( 14 )

#if COMPILING_SHADER_CODE

SamplerState anisoMipmapClampSampler REGISTER_SAMPLER_ANISO_MIPMAP_CLAMP;
SamplerState anisoMipmapWrapUSampler REGISTER_SAMPLER_ANISO_MIPMAP_WRAP_U;
SamplerState anisoMipmapWrapVSampler REGISTER_SAMPLER_ANISO_MIPMAP_WRAP_V;
SamplerState anisoMipmapWrapSampler REGISTER_SAMPLER_ANISO_MIPMAP_WRAP;
SamplerComparisonState shadowmapSampler REGISTER_SAMPLER_SHADOWMAP;
SamplerState pointClampSampler REGISTER_SAMPLER_POINT_CLAMP;
SamplerState pointWrapSampler REGISTER_SAMPLER_POINT_WRAP;
SamplerState pointMipClampSampler REGISTER_SAMPLER_POINT_MIP_CLAMP;
SamplerState linearClampSampler REGISTER_SAMPLER_LINEAR_CLAMP;
SamplerState linearWrapSampler REGISTER_SAMPLER_LINEAR_WRAP;
SamplerState linearMipClampSampler REGISTER_SAMPLER_LINEAR_MIP_CLAMP;
SamplerState linearMipLinearClampSampler REGISTER_SAMPLER_LINEAR_MIP_LINEAR_CLAMP;
SamplerState linearMipmapWrapUSampler REGISTER_SAMPLER_LINEAR_MIPMAP_WRAP_U;
SamplerState linearMipmapWrapVSampler REGISTER_SAMPLER_LINEAR_MIPMAP_WRAP_V;
SamplerState linearMipLinearWrapSampler REGISTER_SAMPLER_LINEAR_MIP_LINEAR_WRAP;

#else // #if COMPILING_SHADER_CODE



#endif // #else // #if COMPILING_SHADER_CODE

#endif // GLOBAL_SAMPLERS_HLSL
